//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabPerfom.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMember
    {
        public int id { get; set; }
        public int PId { get; set; }
        public int MId { get; set; }
    
        public virtual member member { get; set; }
        public virtual Project Project { get; set; }
    }
}
