//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroH.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int ALog_ID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
        public int Requester_ID { get; set; }
        public int Restaurant_ID { get; set; }
        public int NGO_ID { get; set; }
    }
}
