//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroH.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequest
    {
        public int Request_ID { get; set; }
        public Nullable<System.DateTime> CollectionTime { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public int Assignee_ID { get; set; }
        public int Restaurant_ID { get; set; }
        public int Food_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual FoodItem FoodItem { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
