//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroH.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution
    {
        public int Distribution_ID { get; set; }
        public int Employee_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public int Clt_ID { get; set; }
    }
}
