//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroH.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodItem()
        {
            this.CollectRequests = new HashSet<CollectRequest>();
        }
    
        public int FoodItem_ID { get; set; }
        public int LogRequest_ID { get; set; }
        public int R_ID { get; set; }
        public string FoodName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectRequest> CollectRequests { get; set; }
        public virtual LoginLog LoginLog { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
