//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroH.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGO
    {
        public int NGO_ID { get; set; }
        public string Name { get; set; }
        public string ContactInformation { get; set; }
        public string Address { get; set; }
        public string MissionStatement { get; set; }
        public int NGOLog_ID { get; set; }
    
        public virtual LoginLog LoginLog { get; set; }
    }
}
